# Netlify configuration - This file overrides any settings in the web interface
# Build: npm run build (JavaScript only, no TypeScript)
# Deploy: dist folder

[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  DISABLE_TYPESCRIPT = "true"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
